module.exports = {
    "going_silent":"Going Silent",
    "transaction_successful":"Your Transaction is Successful, going silent",
    "okay_going_silent":"Ok, Going Silent",
    "going_silent_for_now" : "Going Silent for now.",
    "no_screen_found_going_silent": "No screen found, going silent",
    "encounter_problem_going_silent":"Encountered a problem, Going silent",
    "sorry_i_did_not_get_you_going_silent":"sorry, I did not get you, Going silent",
    // slow internet feedback
    "slow_internet":"slow internet, please speak again",
    "unstable_internet":"unstable internet, please speak again",
    "slow_internet_going_silent":"sorry, unable to process, try again with good internet, going silent",
    "axios_error_code_504":"AxiosError: Request failed with status code 504",
    "first_one":"first one",
    "second_one":"second one",
    "third_one":"third one",
    "fourth_one":"fourth one",
    "fifth_one":"fifth one",
    "welcome_feedbacks": [
        "Welcome to Louie Voice! Now, you can do Bank Transfer, with just voice commands! Simply say, Transfer money, or, Check account balance",
        "Welcome to Louie Voice! Banking made easy, with just voice commands. Simply say, Transfer money, or, Check account balance.",
        "Welcome to Louie Voice! Transfer money, with just voice commands!",
        "Please give a command to, Transfer money, or, Check account balance.",
        "What would you like to do? Transfer money? Or, Check account balance?",
        "Would you like to Transfer money? Or, Check account balance?",
        "Please give your command!"
      ],
    "your_available_balance_is": "Your available balance is : ",
    "got_it": "Got it.",
    "reading_payee_name": "Reading Payee Names",
    "found_results": "Found % results",
    "found_result": "Found % result",
    "please_select": "Please Select",
    "or": "Or",
    "please_select_or_read_more": "Please select or read more",
    "no_more_results_please_select": "No more results Please select",
    "selected": "Selected",
    "account_ending_with" : "Account ending with ",
    "you_are_transferring" : "You are transferring",
    "to" : "To",
    "transfer_type" : "Transfer type",
    "please_speak_the_amount_in_rupees":"Please speak the amount in rupees.",
    "please_speak_the_amount_in_indian_rupees": "Please speak the amount in Indian rupees",
    "session_count": "SessionCount",
    "what_would_u_like_to_do_transfer_money_or_check_account_balance": "What would you like to do? Transfer money? Or, Check account balance?",
    "with_account_ending_in": "with account ending in",
    "searching_for": "Searching for"
}